<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Gainsway.MetadataEndpoints</RootNamespace>
    <PackageId>Gainsway.MetadataEndpoints</PackageId>
    <Version>0.0.0</Version>
    <Authors>Engineering</Authors>
    <Company>Gainsway</Company>
    <PackageDescription>This library add metadata endpoints to a .NET Core Api</PackageDescription>
    <RepositoryUrl>https://github.com/gainsway/lib-dotnet-metadata-endpoints</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CSharpier.MSBuild" Version="1.2.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
